import { ParticleEmitterInitializationComponent } from "./emitter_initialization.js";
import { ParticleEmitterLifetimeEventsComponent } from "./emitter_lifetime_events.js";
import { ParticleEmitterLifetimeExpressionComponent } from "./emitter_lifetime_expression.js";
import { ParticleEmitterLifetimeLoopingComponent } from "./emitter_lifetime_looping.js";
import { ParticleEmitterLifetimeOnceComponent } from "./emitter_lifetime_once.js";
import { ParticleEmitterLocalSpaceComponent } from "./emitter_local_space.js";
import { ParticleEmitterRateInstantComponent } from "./emitter_rate_instant.js";
import { ParticleEmitterRateManualComponent } from "./emitter_rate_manual.js";
import { ParticleEmitterRateSteadyComponent } from "./emitter_rate_steady.js";
import { ParticleEmitterShapeBoxComponent } from "./emitter_shape_box.js";
import { ParticleEmitterShapeCustomComponent } from "./emitter_shape_custom.js";
import { ParticleEmitterShapeDiscComponent } from "./emitter_shape_disc.js";
import { ParticleEmitterShapeEntityAabbComponent } from "./emitter_shape_entity_aabb.js";
import { ParticleEmitterShapePointComponent } from "./emitter_shape_point.js";
import { ParticleEmitterShapeSphereComponent } from "./emitter_shape_sphere.js";
import { ParticleParticleAppearanceBillboardComponent } from "./particle_appearance_billboard.js";
import { ParticleParticleAppearanceLightingComponent } from "./particle_appearance_lighting.js";
import { ParticleParticleAppearanceTintingComponent } from "./particle_appearance_tinting.js";
import { ParticleParticleExpireIfInBlocksComponent } from "./particle_expire_if_in_blocks.js";
import { ParticleParticleExpireIfNotInBlocksComponent } from "./particle_expire_if_not_in_blocks.js";
import { ParticleParticleInitialSpeedComponent } from "./particle_initial_speed.js";
import { ParticleParticleInitialSpinComponent } from "./particle_initial_spin.js";
import { ParticleParticleInitializationComponent } from "./particle_initialization.js";
import { ParticleParticleKillPlaneComponent } from "./particle_kill_plane.js";
import { ParticleParticleLifetimeEventsComponent } from "./particle_lifetime_events.js";
import { ParticleParticleLifetimeExpressionComponent } from "./particle_lifetime_expression.js";
import { ParticleParticleMotionCollisionComponent } from "./particle_motion_collision.js";
import { ParticleParticleMotionDynamicComponent } from "./particle_motion_dynamic.js";
import { ParticleParticleMotionParametricComponent } from "./particle_motion_parametric.js";
export type ParticleComponents = {
  "minecraft:particle_appearance_billboard"?: ParticleParticleAppearanceBillboardComponent;
  "minecraft:emitter_local_space"?: ParticleEmitterLocalSpaceComponent;
  "minecraft:emitter_initialization"?: ParticleEmitterInitializationComponent;
  "minecraft:emitter_rate_instant"?: ParticleEmitterRateInstantComponent;
  "minecraft:emitter_rate_steady"?: ParticleEmitterRateSteadyComponent;
  "minecraft:emitter_rate_manual"?: ParticleEmitterRateManualComponent;
  "minecraft:emitter_lifetime_looping"?: ParticleEmitterLifetimeLoopingComponent;
  "minecraft:emitter_lifetime_once"?: ParticleEmitterLifetimeOnceComponent;
  "minecraft:emitter_lifetime_expression"?: ParticleEmitterLifetimeExpressionComponent;
  "minecraft:emitter_lifetime_events"?: ParticleEmitterLifetimeEventsComponent;
  "minecraft:emitter_shape_point"?: ParticleEmitterShapePointComponent;
  "minecraft:emitter_shape_sphere"?: ParticleEmitterShapeSphereComponent;
  "minecraft:emitter_shape_box"?: ParticleEmitterShapeBoxComponent;
  "minecraft:emitter_shape_custom"?: ParticleEmitterShapeCustomComponent;
  "minecraft:emitter_shape_entity_aabb"?: ParticleEmitterShapeEntityAabbComponent;
  "minecraft:emitter_shape_disc"?: ParticleEmitterShapeDiscComponent;
  "minecraft:particle_initial_spin"?: ParticleParticleInitialSpinComponent;
  "minecraft:particle_initial_speed"?: ParticleParticleInitialSpeedComponent;
  "minecraft:particle_motion_dynamic"?: ParticleParticleMotionDynamicComponent;
  "minecraft:particle_motion_parametric"?: ParticleParticleMotionParametricComponent;
  "minecraft:particle_motion_collision"?: ParticleParticleMotionCollisionComponent;
  "minecraft:particle_appearance_tinting"?: ParticleParticleAppearanceTintingComponent;
  "minecraft:particle_appearance_lighting"?: ParticleParticleAppearanceLightingComponent;
  "minecraft:particle_lifetime_expression"?: ParticleParticleLifetimeExpressionComponent;
  "minecraft:particle_lifetime_events"?: ParticleParticleLifetimeEventsComponent;
  "minecraft:particle_expire_if_in_blocks"?: ParticleParticleExpireIfInBlocksComponent;
  "minecraft:particle_expire_if_not_in_blocks"?: ParticleParticleExpireIfNotInBlocksComponent;
  "minecraft:particle_kill_plane"?: ParticleParticleKillPlaneComponent;
  "minecraft:particle_initialization"?: ParticleParticleInitializationComponent;
};
