import { BlockCollisionBoxComponent } from "./collision_box.js";
import { BlockConnectionRuleComponent } from "./connection_rule.js";
import { BlockCraftingTableComponent } from "./crafting_table.js";
import { BlockDestructibleByExplosionComponent } from "./destructible_by_explosion.js";
import { BlockDestructibleByMiningComponent } from "./destructible_by_mining.js";
import { BlockDestructionParticlesComponent } from "./destruction_particles.js";
import { BlockDisplayNameComponent } from "./display_name.js";
import { BlockEmbeddedVisualComponent } from "./embedded_visual.js";
import { BlockEntityFallOnComponent } from "./entity_fall_on.js";
import { BlockFlammableComponent } from "./flammable.js";
import { BlockFlowerPottableComponent } from "./flower_pottable.js";
import { BlockFrictionComponent } from "./friction.js";
import { BlockGeometryComponent } from "./geometry.js";
import { BlockItemVisualComponent } from "./item_visual.js";
import { BlockLeashableComponent } from "./leashable.js";
import { BlockLightDampeningComponent } from "./light_dampening.js";
import { BlockLightEmissionComponent } from "./light_emission.js";
import { BlockLiquidDetectionComponent } from "./liquid_detection.js";
import { BlockLootComponent } from "./loot.js";
import { BlockMapColorComponent } from "./map_color.js";
import { BlockMaterialInstancesComponent } from "./material_instances.js";
import { BlockMovableComponent } from "./movable.js";
import { BlockPlacementFilterComponent } from "./placement_filter.js";
import { BlockPrecipitationInteractionsComponent } from "./precipitation_interactions.js";
import { BlockRandomOffsetComponent } from "./random_offset.js";
import { BlockRedstoneConductivityComponent } from "./redstone_conductivity.js";
import { BlockRedstoneConsumerComponent } from "./redstone_consumer.js";
import { BlockRedstoneProducerComponent } from "./redstone_producer.js";
import { BlockReplaceableComponent } from "./replaceable.js";
import { BlockSelectionBoxComponent } from "./selection_box.js";
import { BlockSupportComponent } from "./support.js";
import { BlockTickComponent } from "./tick.js";
import { BlockTransformationComponent } from "./transformation.js";
export type BlockComponents = {
  "minecraft:collision_box"?: BlockCollisionBoxComponent;
  "minecraft:connection_rule"?: BlockConnectionRuleComponent;
  "minecraft:crafting_table"?: BlockCraftingTableComponent;
  "minecraft:destructible_by_explosion"?: BlockDestructibleByExplosionComponent;
  "minecraft:destructible_by_mining"?: BlockDestructibleByMiningComponent;
  "minecraft:destruction_particles"?: BlockDestructionParticlesComponent;
  "minecraft:display_name"?: BlockDisplayNameComponent;
  "minecraft:embedded_visual"?: BlockEmbeddedVisualComponent;
  "minecraft:entity_fall_on"?: BlockEntityFallOnComponent;
  "minecraft:flammable"?: BlockFlammableComponent;
  "minecraft:flower_pottable"?: BlockFlowerPottableComponent;
  "minecraft:friction"?: BlockFrictionComponent;
  "minecraft:geometry"?: BlockGeometryComponent;
  "minecraft:item_visual"?: BlockItemVisualComponent;
  "minecraft:leashable"?: BlockLeashableComponent;
  "minecraft:loot"?: BlockLootComponent;
  "minecraft:light_dampening"?: BlockLightDampeningComponent;
  "minecraft:light_emission"?: BlockLightEmissionComponent;
  "minecraft:liquid_detection"?: BlockLiquidDetectionComponent;
  "minecraft:map_color"?: BlockMapColorComponent;
  "minecraft:material_instances"?: BlockMaterialInstancesComponent;
  "minecraft:movable"?: BlockMovableComponent;
  "minecraft:placement_filter"?: BlockPlacementFilterComponent;
  "minecraft:precipitation_interactions"?: BlockPrecipitationInteractionsComponent;
  "minecraft:random_offset"?: BlockRandomOffsetComponent;
  "minecraft:redstone_conductivity"?: BlockRedstoneConductivityComponent;
  "minecraft:redstone_consumer"?: BlockRedstoneConsumerComponent;
  "minecraft:redstone_producer"?: BlockRedstoneProducerComponent;
  "minecraft:replaceable"?: BlockReplaceableComponent;
  "minecraft:selection_box"?: BlockSelectionBoxComponent;
  "minecraft:support"?: BlockSupportComponent;
  "minecraft:tick"?: BlockTickComponent;
  "minecraft:transformation"?: BlockTransformationComponent;
};
