import { BlockCollisionBoxComponent } from "./collision_box.js";
import { BlockCraftingTableComponent } from "./crafting_table.js";
import { BlockCustomComponentsComponent } from "./custom_components.js";
import { BlockDestructibleByExplosionComponent } from "./destructible_by_explosion.js";
import { BlockDestructibleByMiningComponent } from "./destructible_by_mining.js";
import { BlockDestructionParticlesComponent } from "./destruction_particles.js";
import { BlockDisplayNameComponent } from "./display_name.js";
import { BlockEntityFallOnComponent } from "./entity_fall_on.js";
import { BlockFlammableComponent } from "./flammable.js";
import { BlockFrictionComponent } from "./friction.js";
import { BlockGeometryComponent } from "./geometry.js";
import { BlockItemVisualComponent } from "./item_visual.js";
import { BlockLightDampeningComponent } from "./light_dampening.js";
import { BlockLightEmissionComponent } from "./light_emission.js";
import { BlockLiquidDetectionComponent } from "./liquid_detection.js";
import { BlockLootComponent } from "./loot.js";
import { BlockMapColorComponent } from "./map_color.js";
import { BlockMaterialInstancesComponent } from "./material_instances.js";
import { BlockPlacementFilterComponent } from "./placement_filter.js";
import { BlockRedstoneConductivityComponent } from "./redstone_conductivity.js";
import { BlockReplaceableComponent } from "./replaceable.js";
import { BlockSelectionBoxComponent } from "./selection_box.js";
import { BlockTickComponent } from "./tick.js";
import { BlockTransformationComponent } from "./transformation.js";
export type BlockComponents = {
  "minecraft:collision_box"?: BlockCollisionBoxComponent;
  "minecraft:crafting_table"?: BlockCraftingTableComponent;
  "minecraft:custom_components"?: BlockCustomComponentsComponent;
  "minecraft:destructible_by_explosion"?: BlockDestructibleByExplosionComponent;
  "minecraft:destructible_by_mining"?: BlockDestructibleByMiningComponent;
  "minecraft:destruction_particles"?: BlockDestructionParticlesComponent;
  "minecraft:display_name"?: BlockDisplayNameComponent;
  "minecraft:entity_fall_on"?: BlockEntityFallOnComponent;
  "minecraft:flammable"?: BlockFlammableComponent;
  "minecraft:friction"?: BlockFrictionComponent;
  "minecraft:geometry"?: BlockGeometryComponent;
  "minecraft:item_visual"?: BlockItemVisualComponent;
  "minecraft:loot"?: BlockLootComponent;
  "minecraft:light_dampening"?: BlockLightDampeningComponent;
  "minecraft:light_emission"?: BlockLightEmissionComponent;
  "minecraft:liquid_detection"?: BlockLiquidDetectionComponent;
  "minecraft:map_color"?: BlockMapColorComponent;
  "minecraft:material_instances"?: BlockMaterialInstancesComponent;
  "minecraft:placement_filter"?: BlockPlacementFilterComponent;
  "minecraft:redstone_conductivity"?: BlockRedstoneConductivityComponent;
  "minecraft:replaceable"?: BlockReplaceableComponent;
  "minecraft:selection_box"?: BlockSelectionBoxComponent;
  "minecraft:tick"?: BlockTickComponent;
  "minecraft:transformation"?: BlockTransformationComponent;
};
