import { LiteralUnion } from "../literal_union.js";

export type BlockTag = LiteralUnion<
  | "wood"
  | "text_sign"
  | "log"
  | "acacia"
  | "plant"
  | "trapdoors"
  | "rail"
  | "fertilize_area"
  | "stone"
  | "not_feature_replaceable"
  | "minecraft:crop"
  | "birch"
  | "pumpkin"
  | "metal"
  | "stone_pick_diggable"
  | "iron_pick_diggable"
  | "diamond_pick_diggable"
  | "dark_oak"
  | "grass"
  | "dirt"
  | "water"
  | "gravel"
  | "jungle"
  | "mob_spawner"
  | "oak"
  | "sand"
  | "snow"
  | "spruce"
>;
