import { LiteralUnion } from "../literal_union.js";

export type LegacyParticle = LiteralUnion<
  | "mobspellambient"
  | "villagerangry"
  | "blockbreak"
  | "blockdust"
  | "bubble"
  | "evaporation"
  | "crit"
  | "dragonbreath"
  | "driplava"
  | "dripwater"
  | "reddust"
  | "spell"
  | "mobappearance"
  | "enchantingtable"
  | "endrod"
  | "mobspell"
  | "largeexplode"
  | "hugeexplosion"
  | "fallingdust"
  | "fireworksspark"
  | "waterwake"
  | "flame"
  | "villagerhappy"
  | "heart"
  | "mobspellinstantaneous"
  | "iconcrack"
  | "slime"
  | "snowballpoof"
  | "largesmoke"
  | "lava"
  | "mobflame"
  | "townaura"
  | "nautilus"
  | "note"
  | "explode"
  | "portal"
  | "rainsplash"
  | "smoke"
  | "watersplash"
  | "ink"
  | "terrain"
  | "totem"
  | "trackingemitter"
  | "witchspell"
>;
