import { ItemAllowOffHandComponent } from "./allow_off_hand.js";
import { ItemArmorComponent } from "./armor.js";
import { ItemBlockPlacerComponent } from "./block_placer.js";
import { ItemCanDestroyInCreativeComponent } from "./can_destroy_in_creative.js";
import { ItemCooldownComponent } from "./cooldown.js";
import { ItemCreativeCategoryComponent } from "./creative_category.js";
import { ItemCustomComponentsComponent } from "./custom_components.js";
import { ItemDamageComponent } from "./damage.js";
import { ItemDamageAbsorptionComponent } from "./damage_absorption.js";
import { ItemDiggerComponent } from "./digger.js";
import { ItemDisplayNameComponent } from "./display_name.js";
import { ItemDurabilityComponent } from "./durability.js";
import { ItemDurabilitySensorComponent } from "./durability_sensor.js";
import { ItemDyePowderComponent } from "./dye_powder.js";
import { ItemEnchantableComponent } from "./enchantable.js";
import { ItemEntityPlacerComponent } from "./entity_placer.js";
import { ItemFertilizerComponent } from "./fertilizer.js";
import { ItemFoodComponent } from "./food.js";
import { ItemFuelComponent } from "./fuel.js";
import { ItemGlintComponent } from "./glint.js";
import { ItemHandEquippedComponent } from "./hand_equipped.js";
import { ItemHoverTextColorComponent } from "./hover_text_color.js";
import { ItemIconComponent } from "./icon.js";
import { ItemIgnoresPermissionComponent } from "./ignores_permission.js";
import { ItemInteractButtonComponent } from "./interact_button.js";
import { ItemKnockbackResistanceComponent } from "./knockback_resistance.js";
import { ItemLiquidClippedComponent } from "./liquid_clipped.js";
import { ItemMaxStackSizeComponent } from "./max_stack_size.js";
import { ItemMiningSpeedComponent } from "./mining_speed.js";
import { ItemMirroredArtComponent } from "./mirrored_art.js";
import { ItemPotionComponent } from "./potion.js";
import { ItemProjectileComponent } from "./projectile.js";
import { ItemRarityComponent } from "./rarity.js";
import { ItemRecordComponent } from "./record.js";
import { ItemRenderOffsetsComponent } from "./render_offsets.js";
import { ItemRepairableComponent } from "./repairable.js";
import { ItemShooterComponent } from "./shooter.js";
import { ItemShouldDespawnComponent } from "./should_despawn.js";
import { ItemStackedByDataComponent } from "./stacked_by_data.js";
import { ItemTagsComponent } from "./tags.js";
import { ItemThrowableComponent } from "./throwable.js";
import { ItemUseAnimationComponent } from "./use_animation.js";
import { ItemUseModifiersComponent } from "./use_modifiers.js";
import { ItemWearableComponent } from "./wearable.js";
export type ItemComponents = {
  "minecraft:allow_off_hand"?: ItemAllowOffHandComponent;
  "minecraft:block_placer"?: ItemBlockPlacerComponent;
  "minecraft:can_destroy_in_creative"?: ItemCanDestroyInCreativeComponent;
  "minecraft:cooldown"?: ItemCooldownComponent;
  "minecraft:custom_components"?: ItemCustomComponentsComponent;
  "minecraft:damage"?: ItemDamageComponent;
  "minecraft:damage_absorption"?: ItemDamageAbsorptionComponent;
  "minecraft:digger"?: ItemDiggerComponent;
  "minecraft:display_name"?: ItemDisplayNameComponent;
  "minecraft:durability"?: ItemDurabilityComponent;
  "minecraft:durability_sensor"?: ItemDurabilitySensorComponent;
  "minecraft:enchantable"?: ItemEnchantableComponent;
  "minecraft:entity_placer"?: ItemEntityPlacerComponent;
  "minecraft:fuel"?: ItemFuelComponent;
  "minecraft:food"?: ItemFoodComponent;
  "minecraft:glint"?: ItemGlintComponent;
  "minecraft:hand_equipped"?: ItemHandEquippedComponent;
  "minecraft:hover_text_color"?: ItemHoverTextColorComponent;
  "minecraft:icon"?: ItemIconComponent;
  "minecraft:interact_button"?: ItemInteractButtonComponent;
  "minecraft:liquid_clipped"?: ItemLiquidClippedComponent;
  "minecraft:max_stack_size"?: ItemMaxStackSizeComponent;
  "minecraft:projectile"?: ItemProjectileComponent;
  "minecraft:rarity"?: ItemRarityComponent;
  "minecraft:record"?: ItemRecordComponent;
  "minecraft:repairable"?: ItemRepairableComponent;
  "minecraft:stacked_by_data"?: ItemStackedByDataComponent;
  "minecraft:should_despawn"?: ItemShouldDespawnComponent;
  "minecraft:shooter"?: ItemShooterComponent;
  "minecraft:tags"?: ItemTagsComponent;
  "minecraft:throwable"?: ItemThrowableComponent;
  "minecraft:use_animation"?: ItemUseAnimationComponent;
  "minecraft:use_modifiers"?: ItemUseModifiersComponent;
  "minecraft:wearable"?: ItemWearableComponent;
  "minecraft:armor"?: ItemArmorComponent;
  "minecraft:creative_category"?: ItemCreativeCategoryComponent;
  "minecraft:dye_powder"?: ItemDyePowderComponent;
  "minecraft:fertilizer"?: ItemFertilizerComponent;
  "minecraft:ignores_permission"?: ItemIgnoresPermissionComponent;
  "minecraft:knockback_resistance"?: ItemKnockbackResistanceComponent;
  "minecraft:mining_speed"?: ItemMiningSpeedComponent;
  "minecraft:mirrored_art"?: ItemMirroredArtComponent;
  "minecraft:potion"?: ItemPotionComponent;
  "minecraft:render_offsets"?: ItemRenderOffsetsComponent;
};
