import { ItemAllowOffHandComponent } from "./allow_off_hand.js";
import { ItemBlockPlacerComponent } from "./block_placer.js";
import { ItemBundleInteractionComponent } from "./bundle_interaction.js";
import { ItemCanDestroyInCreativeComponent } from "./can_destroy_in_creative.js";
import { ItemCompostableComponent } from "./compostable.js";
import { ItemCooldownComponent } from "./cooldown.js";
import { ItemDamageComponent } from "./damage.js";
import { ItemDamageAbsorptionComponent } from "./damage_absorption.js";
import { ItemDiggerComponent } from "./digger.js";
import { ItemDisplayNameComponent } from "./display_name.js";
import { ItemDurabilityComponent } from "./durability.js";
import { ItemDurabilitySensorComponent } from "./durability_sensor.js";
import { ItemDyeableComponent } from "./dyeable.js";
import { ItemEnchantableComponent } from "./enchantable.js";
import { ItemEntityPlacerComponent } from "./entity_placer.js";
import { ItemFireResistantComponent } from "./fire_resistant.js";
import { ItemFoodComponent } from "./food.js";
import { ItemFuelComponent } from "./fuel.js";
import { ItemGlintComponent } from "./glint.js";
import { ItemHandEquippedComponent } from "./hand_equipped.js";
import { ItemHoverTextColorComponent } from "./hover_text_color.js";
import { ItemIconComponent } from "./icon.js";
import { ItemInteractButtonComponent } from "./interact_button.js";
import { ItemLiquidClippedComponent } from "./liquid_clipped.js";
import { ItemMaxStackSizeComponent } from "./max_stack_size.js";
import { ItemPiercingWeaponComponent } from "./piercing_weapon.js";
import { ItemProjectileComponent } from "./projectile.js";
import { ItemRarityComponent } from "./rarity.js";
import { ItemRecordComponent } from "./record.js";
import { ItemRepairableComponent } from "./repairable.js";
import { ItemShooterComponent } from "./shooter.js";
import { ItemShouldDespawnComponent } from "./should_despawn.js";
import { ItemStackedByDataComponent } from "./stacked_by_data.js";
import { ItemStorageItemComponent } from "./storage_item.js";
import { ItemStorageWeightLimitComponent } from "./storage_weight_limit.js";
import { ItemStorageWeightModifierComponent } from "./storage_weight_modifier.js";
import { ItemSwingDurationComponent } from "./swing_duration.js";
import { ItemSwingSoundsComponent } from "./swing_sounds.js";
import { ItemTagsComponent } from "./tags.js";
import { ItemThrowableComponent } from "./throwable.js";
import { ItemUseAnimationComponent } from "./use_animation.js";
import { ItemUseModifiersComponent } from "./use_modifiers.js";
import { ItemWearableComponent } from "./wearable.js";
export type ItemComponents = {
  "minecraft:allow_off_hand"?: ItemAllowOffHandComponent;
  "minecraft:block_placer"?: ItemBlockPlacerComponent;
  "minecraft:bundle_interaction"?: ItemBundleInteractionComponent;
  "minecraft:can_destroy_in_creative"?: ItemCanDestroyInCreativeComponent;
  "minecraft:compostable"?: ItemCompostableComponent;
  "minecraft:cooldown"?: ItemCooldownComponent;
  "minecraft:damage"?: ItemDamageComponent;
  "minecraft:damage_absorption"?: ItemDamageAbsorptionComponent;
  "minecraft:digger"?: ItemDiggerComponent;
  "minecraft:display_name"?: ItemDisplayNameComponent;
  "minecraft:durability"?: ItemDurabilityComponent;
  "minecraft:durability_sensor"?: ItemDurabilitySensorComponent;
  "minecraft:dyeable"?: ItemDyeableComponent;
  "minecraft:enchantable"?: ItemEnchantableComponent;
  "minecraft:entity_placer"?: ItemEntityPlacerComponent;
  "minecraft:fire_resistant"?: ItemFireResistantComponent;
  "minecraft:food"?: ItemFoodComponent;
  "minecraft:fuel"?: ItemFuelComponent;
  "minecraft:glint"?: ItemGlintComponent;
  "minecraft:hand_equipped"?: ItemHandEquippedComponent;
  "minecraft:hover_text_color"?: ItemHoverTextColorComponent;
  "minecraft:icon"?: ItemIconComponent;
  "minecraft:interact_button"?: ItemInteractButtonComponent;
  "minecraft:liquid_clipped"?: ItemLiquidClippedComponent;
  "minecraft:max_stack_size"?: ItemMaxStackSizeComponent;
  "minecraft:piercing_weapon"?: ItemPiercingWeaponComponent;
  "minecraft:projectile"?: ItemProjectileComponent;
  "minecraft:rarity"?: ItemRarityComponent;
  "minecraft:record"?: ItemRecordComponent;
  "minecraft:repairable"?: ItemRepairableComponent;
  "minecraft:shooter"?: ItemShooterComponent;
  "minecraft:should_despawn"?: ItemShouldDespawnComponent;
  "minecraft:stacked_by_data"?: ItemStackedByDataComponent;
  "minecraft:storage_item"?: ItemStorageItemComponent;
  "minecraft:storage_weight_limit"?: ItemStorageWeightLimitComponent;
  "minecraft:storage_weight_modifier"?: ItemStorageWeightModifierComponent;
  "minecraft:swing_duration"?: ItemSwingDurationComponent;
  "minecraft:swing_sounds"?: ItemSwingSoundsComponent;
  "minecraft:use_animation"?: ItemUseAnimationComponent;
  "minecraft:use_modifiers"?: ItemUseModifiersComponent;
  "minecraft:tags"?: ItemTagsComponent;
  "minecraft:throwable"?: ItemThrowableComponent;
  "minecraft:wearable"?: ItemWearableComponent;
};
