import { EntityAddriderComponent } from "./addrider.js";
import { EntityAdmireItemComponent } from "./admire_item.js";
import { EntityAgeableComponent } from "./ageable.js";
import { EntityAmbientSoundIntervalComponent } from "./ambient_sound_interval.js";
import { EntityAngerLevelComponent } from "./anger_level.js";
import { EntityAngryComponent } from "./angry.js";
import { EntityAnnotationBreakDoorComponent } from "./annotation.break_door.js";
import { EntityAnnotationOpenDoorComponent } from "./annotation.open_door.js";
import { EntityAreaAttackComponent } from "./area_attack.js";
import { EntityAttackComponent } from "./attack.js";
import { EntityAttackCooldownComponent } from "./attack_cooldown.js";
import { EntityAttackDamageComponent } from "./attack_damage.js";
import { EntityBalloonableComponent } from "./balloonable.js";
import { EntityBarterComponent } from "./barter.js";
import { EntityBehaviorAdmireItemComponent } from "./behavior.admire_item.js";
import { EntityBehaviorAvoidBlockComponent } from "./behavior.avoid_block.js";
import { EntityBehaviorAvoidMobTypeComponent } from "./behavior.avoid_mob_type.js";
import { EntityBehaviorBarterComponent } from "./behavior.barter.js";
import { EntityBehaviorBegComponent } from "./behavior.beg.js";
import { EntityBehaviorBreakDoorComponent } from "./behavior.break_door.js";
import { EntityBehaviorBreedComponent } from "./behavior.breed.js";
import { EntityBehaviorCelebrateComponent } from "./behavior.celebrate.js";
import { EntityBehaviorCelebrateSurviveComponent } from "./behavior.celebrate_survive.js";
import { EntityBehaviorChargeAttackComponent } from "./behavior.charge_attack.js";
import { EntityBehaviorChargeHeldItemComponent } from "./behavior.charge_held_item.js";
import { EntityBehaviorCircleAroundAnchorComponent } from "./behavior.circle_around_anchor.js";
import { EntityBehaviorControlledByPlayerComponent } from "./behavior.controlled_by_player.js";
import { EntityBehaviorCroakComponent } from "./behavior.croak.js";
import { EntityBehaviorDefendTrustedTargetComponent } from "./behavior.defend_trusted_target.js";
import { EntityBehaviorDefendVillageTargetComponent } from "./behavior.defend_village_target.js";
import { EntityBehaviorDelayedAttackComponent } from "./behavior.delayed_attack.js";
import { EntityBehaviorDigComponent } from "./behavior.dig.js";
import { EntityBehaviorDoorInteractComponent } from "./behavior.door_interact.js";
import { EntityBehaviorDragonchargeplayerComponent } from "./behavior.dragonchargeplayer.js";
import { EntityBehaviorDragondeathComponent } from "./behavior.dragondeath.js";
import { EntityBehaviorDragonflamingComponent } from "./behavior.dragonflaming.js";
import { EntityBehaviorDragonholdingpatternComponent } from "./behavior.dragonholdingpattern.js";
import { EntityBehaviorDragonlandingComponent } from "./behavior.dragonlanding.js";
import { EntityBehaviorDragonscanningComponent } from "./behavior.dragonscanning.js";
import { EntityBehaviorDragonstrafeplayerComponent } from "./behavior.dragonstrafeplayer.js";
import { EntityBehaviorDragontakeoffComponent } from "./behavior.dragontakeoff.js";
import { EntityBehaviorDrinkMilkComponent } from "./behavior.drink_milk.js";
import { EntityBehaviorDrinkPotionComponent } from "./behavior.drink_potion.js";
import { EntityBehaviorDropItemForComponent } from "./behavior.drop_item_for.js";
import { EntityBehaviorEatBlockComponent } from "./behavior.eat_block.js";
import { EntityBehaviorEatCarriedItemComponent } from "./behavior.eat_carried_item.js";
import { EntityBehaviorEatMobComponent } from "./behavior.eat_mob.js";
import { EntityBehaviorEmergeComponent } from "./behavior.emerge.js";
import { EntityBehaviorEndermanLeaveBlockComponent } from "./behavior.enderman_leave_block.js";
import { EntityBehaviorEndermanTakeBlockComponent } from "./behavior.enderman_take_block.js";
import { EntityBehaviorEquipItemComponent } from "./behavior.equip_item.js";
import { EntityBehaviorExploreOutskirtsComponent } from "./behavior.explore_outskirts.js";
import { EntityBehaviorFertilizeFarmBlockComponent } from "./behavior.fertilize_farm_block.js";
import { EntityBehaviorFindCoverComponent } from "./behavior.find_cover.js";
import { EntityBehaviorFindMountComponent } from "./behavior.find_mount.js";
import { EntityBehaviorFindUnderwaterTreasureComponent } from "./behavior.find_underwater_treasure.js";
import { EntityBehaviorFireAtTargetComponent } from "./behavior.fire_at_target.js";
import { EntityBehaviorFleeSunComponent } from "./behavior.flee_sun.js";
import { EntityBehaviorFloatComponent } from "./behavior.float.js";
import { EntityBehaviorFloatTemptComponent } from "./behavior.float_tempt.js";
import { EntityBehaviorFloatWanderComponent } from "./behavior.float_wander.js";
import { EntityBehaviorFollowCaravanComponent } from "./behavior.follow_caravan.js";
import { EntityBehaviorFollowMobComponent } from "./behavior.follow_mob.js";
import { EntityBehaviorFollowOwnerComponent } from "./behavior.follow_owner.js";
import { EntityBehaviorFollowParentComponent } from "./behavior.follow_parent.js";
import { EntityBehaviorFollowTargetCaptainComponent } from "./behavior.follow_target_captain.js";
import { EntityBehaviorGoAndGiveItemsToNoteblockComponent } from "./behavior.go_and_give_items_to_noteblock.js";
import { EntityBehaviorGoAndGiveItemsToOwnerComponent } from "./behavior.go_and_give_items_to_owner.js";
import { EntityBehaviorGoHomeComponent } from "./behavior.go_home.js";
import { EntityBehaviorGuardianAttackComponent } from "./behavior.guardian_attack.js";
import { EntityBehaviorHarvestFarmBlockComponent } from "./behavior.harvest_farm_block.js";
import { EntityBehaviorHideComponent } from "./behavior.hide.js";
import { EntityBehaviorHoldGroundComponent } from "./behavior.hold_ground.js";
import { EntityBehaviorHoverComponent } from "./behavior.hover.js";
import { EntityBehaviorHurtByTargetComponent } from "./behavior.hurt_by_target.js";
import { EntityBehaviorInspectBookshelfComponent } from "./behavior.inspect_bookshelf.js";
import { EntityBehaviorInvestigateSuspiciousLocationComponent } from "./behavior.investigate_suspicious_location.js";
import { EntityBehaviorJumpAroundTargetComponent } from "./behavior.jump_around_target.js";
import { EntityBehaviorJumpToBlockComponent } from "./behavior.jump_to_block.js";
import { EntityBehaviorKnockbackRoarComponent } from "./behavior.knockback_roar.js";
import { EntityBehaviorLayDownComponent } from "./behavior.lay_down.js";
import { EntityBehaviorLayEggComponent } from "./behavior.lay_egg.js";
import { EntityBehaviorLeapAtTargetComponent } from "./behavior.leap_at_target.js";
import { EntityBehaviorLookAtEntityComponent } from "./behavior.look_at_entity.js";
import { EntityBehaviorLookAtPlayerComponent } from "./behavior.look_at_player.js";
import { EntityBehaviorLookAtTargetComponent } from "./behavior.look_at_target.js";
import { EntityBehaviorLookAtTradingPlayerComponent } from "./behavior.look_at_trading_player.js";
import { EntityBehaviorMakeLoveComponent } from "./behavior.make_love.js";
import { EntityBehaviorMeleeAttackComponent } from "./behavior.melee_attack.js";
import { EntityBehaviorMeleeBoxAttackComponent } from "./behavior.melee_box_attack.js";
import { EntityBehaviorMingleComponent } from "./behavior.mingle.js";
import { EntityBehaviorMountPathingComponent } from "./behavior.mount_pathing.js";
import { EntityBehaviorMoveAroundTargetComponent } from "./behavior.move_around_target.js";
import { EntityBehaviorMoveAwayFromTargetComponent } from "./behavior.move_away_from_target.js";
import { EntityBehaviorMoveIndoorsComponent } from "./behavior.move_indoors.js";
import { EntityBehaviorMoveOutdoorsComponent } from "./behavior.move_outdoors.js";
import { EntityBehaviorMoveThroughVillageComponent } from "./behavior.move_through_village.js";
import { EntityBehaviorMoveToBlockComponent } from "./behavior.move_to_block.js";
import { EntityBehaviorMoveToLandComponent } from "./behavior.move_to_land.js";
import { EntityBehaviorMoveToLavaComponent } from "./behavior.move_to_lava.js";
import { EntityBehaviorMoveToLiquidComponent } from "./behavior.move_to_liquid.js";
import { EntityBehaviorMoveToPoiComponent } from "./behavior.move_to_poi.js";
import { EntityBehaviorMoveToRandomBlockComponent } from "./behavior.move_to_random_block.js";
import { EntityBehaviorMoveToVillageComponent } from "./behavior.move_to_village.js";
import { EntityBehaviorMoveToWaterComponent } from "./behavior.move_to_water.js";
import { EntityBehaviorMoveTowardsDwellingRestrictionComponent } from "./behavior.move_towards_dwelling_restriction.js";
import { EntityBehaviorMoveTowardsHomeRestrictionComponent } from "./behavior.move_towards_home_restriction.js";
import { EntityBehaviorMoveTowardsTargetComponent } from "./behavior.move_towards_target.js";
import { EntityBehaviorNapComponent } from "./behavior.nap.js";
import { EntityBehaviorNearestAttackableTargetComponent } from "./behavior.nearest_attackable_target.js";
import { EntityBehaviorNearestPrioritizedAttackableTargetComponent } from "./behavior.nearest_prioritized_attackable_target.js";
import { EntityBehaviorOcelotSitOnBlockComponent } from "./behavior.ocelot_sit_on_block.js";
import { EntityBehaviorOcelotattackComponent } from "./behavior.ocelotattack.js";
import { EntityBehaviorOfferFlowerComponent } from "./behavior.offer_flower.js";
import { EntityBehaviorOpenDoorComponent } from "./behavior.open_door.js";
import { EntityBehaviorOwnerHurtByTargetComponent } from "./behavior.owner_hurt_by_target.js";
import { EntityBehaviorOwnerHurtTargetComponent } from "./behavior.owner_hurt_target.js";
import { EntityBehaviorPanicComponent } from "./behavior.panic.js";
import { EntityBehaviorPetSleepWithOwnerComponent } from "./behavior.pet_sleep_with_owner.js";
import { EntityBehaviorPickupItemsComponent } from "./behavior.pickup_items.js";
import { EntityBehaviorPlaceBlockComponent } from "./behavior.place_block.js";
import { EntityBehaviorPlayComponent } from "./behavior.play.js";
import { EntityBehaviorPlayDeadComponent } from "./behavior.play_dead.js";
import { EntityBehaviorPlayerRideTamedComponent } from "./behavior.player_ride_tamed.js";
import { EntityBehaviorRaidGardenComponent } from "./behavior.raid_garden.js";
import { EntityBehaviorRamAttackComponent } from "./behavior.ram_attack.js";
import { EntityBehaviorRandomBreachComponent } from "./behavior.random_breach.js";
import { EntityBehaviorRandomFlyComponent } from "./behavior.random_fly.js";
import { EntityBehaviorRandomHoverComponent } from "./behavior.random_hover.js";
import { EntityBehaviorRandomLookAroundComponent } from "./behavior.random_look_around.js";
import { EntityBehaviorRandomLookAroundAndSitComponent } from "./behavior.random_look_around_and_sit.js";
import { EntityBehaviorRandomSearchAndDigComponent } from "./behavior.random_search_and_dig.js";
import { EntityBehaviorRandomSittingComponent } from "./behavior.random_sitting.js";
import { EntityBehaviorRandomStrollComponent } from "./behavior.random_stroll.js";
import { EntityBehaviorRandomSwimComponent } from "./behavior.random_swim.js";
import { EntityBehaviorRangedAttackComponent } from "./behavior.ranged_attack.js";
import { EntityBehaviorRecieveLoveComponent } from "./behavior.recieve_love.js";
import { EntityBehaviorRestrictOpenDoorComponent } from "./behavior.restrict_open_door.js";
import { EntityBehaviorRestrictSunComponent } from "./behavior.restrict_sun.js";
import { EntityBehaviorRiseToLiquidLevelComponent } from "./behavior.rise_to_liquid_level.js";
import { EntityBehaviorRoarComponent } from "./behavior.roar.js";
import { EntityBehaviorRollComponent } from "./behavior.roll.js";
import { EntityBehaviorRunAroundLikeCrazyComponent } from "./behavior.run_around_like_crazy.js";
import { EntityBehaviorScaredComponent } from "./behavior.scared.js";
import { EntityBehaviorSendEventComponent } from "./behavior.send_event.js";
import { EntityBehaviorShareItemsComponent } from "./behavior.share_items.js";
import { EntityBehaviorSilverfishMergeWithStoneComponent } from "./behavior.silverfish_merge_with_stone.js";
import { EntityBehaviorSilverfishWakeUpFriendsComponent } from "./behavior.silverfish_wake_up_friends.js";
import { EntityBehaviorSkeletonHorseTrapComponent } from "./behavior.skeleton_horse_trap.js";
import { EntityBehaviorSleepComponent } from "./behavior.sleep.js";
import { EntityBehaviorSlimeAttackComponent } from "./behavior.slime_attack.js";
import { EntityBehaviorSlimeFloatComponent } from "./behavior.slime_float.js";
import { EntityBehaviorSlimeKeepOnJumpingComponent } from "./behavior.slime_keep_on_jumping.js";
import { EntityBehaviorSlimeRandomDirectionComponent } from "./behavior.slime_random_direction.js";
import { EntityBehaviorSnackingComponent } from "./behavior.snacking.js";
import { EntityBehaviorSneezeComponent } from "./behavior.sneeze.js";
import { EntityBehaviorSniffComponent } from "./behavior.sniff.js";
import { EntityBehaviorSonicBoomComponent } from "./behavior.sonic_boom.js";
import { EntityBehaviorSquidDiveComponent } from "./behavior.squid_dive.js";
import { EntityBehaviorSquidFleeComponent } from "./behavior.squid_flee.js";
import { EntityBehaviorSquidIdleComponent } from "./behavior.squid_idle.js";
import { EntityBehaviorSquidMoveAwayFromGroundComponent } from "./behavior.squid_move_away_from_ground.js";
import { EntityBehaviorSquidOutOfWaterComponent } from "./behavior.squid_out_of_water.js";
import { EntityBehaviorStalkAndPounceOnTargetComponent } from "./behavior.stalk_and_pounce_on_target.js";
import { EntityBehaviorStayNearNoteblockComponent } from "./behavior.stay_near_noteblock.js";
import { EntityBehaviorStayWhileSittingComponent } from "./behavior.stay_while_sitting.js";
import { EntityBehaviorStompAttackComponent } from "./behavior.stomp_attack.js";
import { EntityBehaviorStompTurtleEggComponent } from "./behavior.stomp_turtle_egg.js";
import { EntityBehaviorStrollTowardsVillageComponent } from "./behavior.stroll_towards_village.js";
import { EntityBehaviorSummonEntityComponent } from "./behavior.summon_entity.js";
import { EntityBehaviorSwellComponent } from "./behavior.swell.js";
import { EntityBehaviorSwimIdleComponent } from "./behavior.swim_idle.js";
import { EntityBehaviorSwimUpForBreathComponent } from "./behavior.swim_up_for_breath.js";
import { EntityBehaviorSwimWanderComponent } from "./behavior.swim_wander.js";
import { EntityBehaviorSwimWithEntityComponent } from "./behavior.swim_with_entity.js";
import { EntityBehaviorSwoopAttackComponent } from "./behavior.swoop_attack.js";
import { EntityBehaviorTakeBlockComponent } from "./behavior.take_block.js";
import { EntityBehaviorTakeFlowerComponent } from "./behavior.take_flower.js";
import { EntityBehaviorTeleportToOwnerComponent } from "./behavior.teleport_to_owner.js";
import { EntityBehaviorTemptComponent } from "./behavior.tempt.js";
import { EntityBehaviorTimerFlag1Component } from "./behavior.timer_flag_1.js";
import { EntityBehaviorTimerFlag2Component } from "./behavior.timer_flag_2.js";
import { EntityBehaviorTimerFlag3Component } from "./behavior.timer_flag_3.js";
import { EntityBehaviorTradeInterestComponent } from "./behavior.trade_interest.js";
import { EntityBehaviorTradeWithPlayerComponent } from "./behavior.trade_with_player.js";
import { EntityBehaviorVexCopyOwnerTargetComponent } from "./behavior.vex_copy_owner_target.js";
import { EntityBehaviorVexRandomMoveComponent } from "./behavior.vex_random_move.js";
import { EntityBehaviorWitherRandomAttackPosGoalComponent } from "./behavior.wither_random_attack_pos_goal.js";
import { EntityBehaviorWitherTargetHighestDamageComponent } from "./behavior.wither_target_highest_damage.js";
import { EntityBehaviorWorkComponent } from "./behavior.work.js";
import { EntityBehaviorWorkComposterComponent } from "./behavior.work_composter.js";
import { EntityBlockClimberComponent } from "./block_climber.js";
import { EntityBlockSensorComponent } from "./block_sensor.js";
import { EntityBodyRotationAlwaysFollowsHeadComponent } from "./body_rotation_always_follows_head.js";
import { EntityBodyRotationBlockedComponent } from "./body_rotation_blocked.js";
import { EntityBoostableComponent } from "./boostable.js";
import { EntityBossComponent } from "./boss.js";
import { EntityBreakBlocksComponent } from "./break_blocks.js";
import { EntityBreathableComponent } from "./breathable.js";
import { EntityBreedableComponent } from "./breedable.js";
import { EntityBribeableComponent } from "./bribeable.js";
import { EntityBuoyantComponent } from "./buoyant.js";
import { EntityBurnsInDaylightComponent } from "./burns_in_daylight.js";
import { EntityCanClimbComponent } from "./can_climb.js";
import { EntityCanFlyComponent } from "./can_fly.js";
import { EntityCanJoinRaidComponent } from "./can_join_raid.js";
import { EntityCanPowerJumpComponent } from "./can_power_jump.js";
import { EntityCannotBeAttackedComponent } from "./cannot_be_attacked.js";
import { EntityCelebrateHuntComponent } from "./celebrate_hunt.js";
import { EntityCollisionBoxComponent } from "./collision_box.js";
import { EntityColorComponent } from "./color.js";
import { EntityColor2Component } from "./color2.js";
import { EntityCombatRegenerationComponent } from "./combat_regeneration.js";
import { EntityConditionalBandwidthOptimizationComponent } from "./conditional_bandwidth_optimization.js";
import { EntityCustomHitTestComponent } from "./custom_hit_test.js";
import { EntityDamageOverTimeComponent } from "./damage_over_time.js";
import { EntityDamageSensorComponent } from "./damage_sensor.js";
import { EntityDashComponent } from "./dash.js";
import { EntityDefaultLookAngleComponent } from "./default_look_angle.js";
import { EntityDespawnComponent } from "./despawn.js";
import { EntityDimensionBoundComponent } from "./dimension_bound.js";
import { EntityDryingOutTimerComponent } from "./drying_out_timer.js";
import { EntityDwellerComponent } from "./dweller.js";
import { EntityEconomyTradeTableComponent } from "./economy_trade_table.js";
import { EntityEntitySensorComponent } from "./entity_sensor.js";
import { EntityEnvironmentSensorComponent } from "./environment_sensor.js";
import { EntityEquipItemComponent } from "./equip_item.js";
import { EntityEquipmentComponent } from "./equipment.js";
import { EntityEquippableComponent } from "./equippable.js";
import { EntityExhaustionValuesComponent } from "./exhaustion_values.js";
import { EntityExperienceRewardComponent } from "./experience_reward.js";
import { EntityExplodeComponent } from "./explode.js";
import { EntityFireImmuneComponent } from "./fire_immune.js";
import { EntityFloatsInLiquidComponent } from "./floats_in_liquid.js";
import { EntityFlockingComponent } from "./flocking.js";
import { EntityFlyingSpeedComponent } from "./flying_speed.js";
import { EntityFollowRangeComponent } from "./follow_range.js";
import { EntityFrictionModifierComponent } from "./friction_modifier.js";
import { EntityGameEventMovementTrackingComponent } from "./game_event_movement_tracking.js";
import { EntityGeneticsComponent } from "./genetics.js";
import { EntityGiveableComponent } from "./giveable.js";
import { EntityGroundOffsetComponent } from "./ground_offset.js";
import { EntityGroupSizeComponent } from "./group_size.js";
import { EntityGrowsCropComponent } from "./grows_crop.js";
import { EntityHealableComponent } from "./healable.js";
import { EntityHealthComponent } from "./health.js";
import { EntityHeartbeatComponent } from "./heartbeat.js";
import { EntityHideComponent } from "./hide.js";
import { EntityHomeComponent } from "./home.js";
import { EntityHorseJumpStrengthComponent } from "./horse.jump_strength.js";
import { EntityHurtOnConditionComponent } from "./hurt_on_condition.js";
import { EntityIgnoreCannotBeAttackedComponent } from "./ignore_cannot_be_attacked.js";
import { EntityInputAirControlledComponent } from "./input_air_controlled.js";
import { EntityInputGroundControlledComponent } from "./input_ground_controlled.js";
import { EntityInsideBlockNotifierComponent } from "./inside_block_notifier.js";
import { EntityInsomniaComponent } from "./insomnia.js";
import { EntityInstantDespawnComponent } from "./instant_despawn.js";
import { EntityInteractComponent } from "./interact.js";
import { EntityInventoryComponent } from "./inventory.js";
import { EntityIsBabyComponent } from "./is_baby.js";
import { EntityIsChargedComponent } from "./is_charged.js";
import { EntityIsChestedComponent } from "./is_chested.js";
import { EntityIsCollidableComponent } from "./is_collidable.js";
import { EntityIsDyeableComponent } from "./is_dyeable.js";
import { EntityIsHiddenWhenInvisibleComponent } from "./is_hidden_when_invisible.js";
import { EntityIsIgnitedComponent } from "./is_ignited.js";
import { EntityIsIllagerCaptainComponent } from "./is_illager_captain.js";
import { EntityIsSaddledComponent } from "./is_saddled.js";
import { EntityIsShakingComponent } from "./is_shaking.js";
import { EntityIsShearedComponent } from "./is_sheared.js";
import { EntityIsStackableComponent } from "./is_stackable.js";
import { EntityIsStunnedComponent } from "./is_stunned.js";
import { EntityIsTamedComponent } from "./is_tamed.js";
import { EntityItemControllableComponent } from "./item_controllable.js";
import { EntityItemHopperComponent } from "./item_hopper.js";
import { EntityJumpDynamicComponent } from "./jump.dynamic.js";
import { EntityJumpStaticComponent } from "./jump.static.js";
import { EntityKnockbackResistanceComponent } from "./knockback_resistance.js";
import { EntityLavaMovementComponent } from "./lava_movement.js";
import { EntityLeashableComponent } from "./leashable.js";
import { EntityLeashableToComponent } from "./leashable_to.js";
import { EntityLookedAtComponent } from "./looked_at.js";
import { EntityLootComponent } from "./loot.js";
import { EntityManagedWanderingTraderComponent } from "./managed_wandering_trader.js";
import { EntityMarkVariantComponent } from "./mark_variant.js";
import { EntityMobEffectComponent } from "./mob_effect.js";
import { EntityMobEffectImmunityComponent } from "./mob_effect_immunity.js";
import { EntityMovementAmphibiousComponent } from "./movement.amphibious.js";
import { EntityMovementBasicComponent } from "./movement.basic.js";
import { EntityMovementFlyComponent } from "./movement.fly.js";
import { EntityMovementGenericComponent } from "./movement.generic.js";
import { EntityMovementGlideComponent } from "./movement.glide.js";
import { EntityMovementHoverComponent } from "./movement.hover.js";
import { EntityMovementComponent } from "./movement.js";
import { EntityMovementJumpComponent } from "./movement.jump.js";
import { EntityMovementSkipComponent } from "./movement.skip.js";
import { EntityMovementSwayComponent } from "./movement.sway.js";
import { EntityMovementSoundDistanceOffsetComponent } from "./movement_sound_distance_offset.js";
import { EntityNameableComponent } from "./nameable.js";
import { EntityNavigationClimbComponent } from "./navigation.climb.js";
import { EntityNavigationFloatComponent } from "./navigation.float.js";
import { EntityNavigationFlyComponent } from "./navigation.fly.js";
import { EntityNavigationGenericComponent } from "./navigation.generic.js";
import { EntityNavigationHoverComponent } from "./navigation.hover.js";
import { EntityNavigationSwimComponent } from "./navigation.swim.js";
import { EntityNavigationWalkComponent } from "./navigation.walk.js";
import { EntityNpcComponent } from "./npc.js";
import { EntityOnDeathComponent } from "./on_death.js";
import { EntityOnFriendlyAngerComponent } from "./on_friendly_anger.js";
import { EntityOnHurtComponent } from "./on_hurt.js";
import { EntityOnHurtByPlayerComponent } from "./on_hurt_by_player.js";
import { EntityOnIgniteComponent } from "./on_ignite.js";
import { EntityOnStartLandingComponent } from "./on_start_landing.js";
import { EntityOnStartTakeoffComponent } from "./on_start_takeoff.js";
import { EntityOnTargetAcquiredComponent } from "./on_target_acquired.js";
import { EntityOnTargetEscapeComponent } from "./on_target_escape.js";
import { EntityOnWakeWithOwnerComponent } from "./on_wake_with_owner.js";
import { EntityOutOfControlComponent } from "./out_of_control.js";
import { EntityPeekComponent } from "./peek.js";
import { EntityPersistentComponent } from "./persistent.js";
import { EntityPhysicsComponent } from "./physics.js";
import { EntityPlayerExhaustionComponent } from "./player.exhaustion.js";
import { EntityPlayerExperienceComponent } from "./player.experience.js";
import { EntityPlayerLevelComponent } from "./player.level.js";
import { EntityPlayerSaturationComponent } from "./player.saturation.js";
import { EntityPreferredPathComponent } from "./preferred_path.js";
import { EntityProjectileComponent } from "./projectile.js";
import { EntityPushThroughComponent } from "./push_through.js";
import { EntityPushableComponent } from "./pushable.js";
import { EntityRaidTriggerComponent } from "./raid_trigger.js";
import { EntityRailMovementComponent } from "./rail_movement.js";
import { EntityRailSensorComponent } from "./rail_sensor.js";
import { EntityRavagerBlockedComponent } from "./ravager_blocked.js";
import { EntityReflectProjectilesComponent } from "./reflect_projectiles.js";
import { EntityRemoveInPeacefulComponent } from "./remove_in_peaceful.js";
import { EntityRendersWhenInvisibleComponent } from "./renders_when_invisible.js";
import { EntityRideableComponent } from "./rideable.js";
import { EntityRotationAxisAlignedComponent } from "./rotation_axis_aligned.js";
import { EntityScaleComponent } from "./scale.js";
import { EntityScaleByAgeComponent } from "./scale_by_age.js";
import { EntitySchedulerComponent } from "./scheduler.js";
import { EntityShareablesComponent } from "./shareables.js";
import { EntityShooterComponent } from "./shooter.js";
import { EntitySittableComponent } from "./sittable.js";
import { EntitySkinIdComponent } from "./skin_id.js";
import { EntitySoundVolumeComponent } from "./sound_volume.js";
import { EntitySpawnEntityComponent } from "./spawn_entity.js";
import { EntitySpellEffectsComponent } from "./spell_effects.js";
import { EntityStrengthComponent } from "./strength.js";
import { EntitySuspectTrackingComponent } from "./suspect_tracking.js";
import { EntityTameableComponent } from "./tameable.js";
import { EntityTamemountComponent } from "./tamemount.js";
import { EntityTargetNearbySensorComponent } from "./target_nearby_sensor.js";
import { EntityTeleportComponent } from "./teleport.js";
import { EntityTickWorldComponent } from "./tick_world.js";
import { EntityTimerComponent } from "./timer.js";
import { EntityTradeResupplyComponent } from "./trade_resupply.js";
import { EntityTradeTableComponent } from "./trade_table.js";
import { EntityTrailComponent } from "./trail.js";
import { EntityTransformationComponent } from "./transformation.js";
import { EntityTransientComponent } from "./transient.js";
import { EntityTrustComponent } from "./trust.js";
import { EntityTrustingComponent } from "./trusting.js";
import { EntityTypeFamilyComponent } from "./type_family.js";
import { EntityUnderwaterMovementComponent } from "./underwater_movement.js";
import { EntityVariableMaxAutoStepComponent } from "./variable_max_auto_step.js";
import { EntityVariantComponent } from "./variant.js";
import { EntityVibrationDamperComponent } from "./vibration_damper.js";
import { EntityVibrationListenerComponent } from "./vibration_listener.js";
import { EntityWalkAnimationSpeedComponent } from "./walk_animation_speed.js";
import { EntityWantsJockeyComponent } from "./wants_jockey.js";
import { EntityWaterMovementComponent } from "./water_movement.js";
import { EntityWindBurstComponent } from "./wind_burst.js";
export namespace EntityComponents {
  export type Annotations = {
    "minecraft:annotation.open_door"?: EntityAnnotationOpenDoorComponent;
    "minecraft:annotation.break_door"?: EntityAnnotationBreakDoorComponent;
  };
  export type Behaviors = {
    "minecraft:behavior.dig"?: EntityBehaviorDigComponent;
    "minecraft:behavior.go_and_give_items_to_noteblock"?: EntityBehaviorGoAndGiveItemsToNoteblockComponent;
    "minecraft:behavior.go_and_give_items_to_owner"?: EntityBehaviorGoAndGiveItemsToOwnerComponent;
    "minecraft:behavior.croak"?: EntityBehaviorCroakComponent;
    "minecraft:behavior.eat_mob"?: EntityBehaviorEatMobComponent;
    "minecraft:behavior.emerge"?: EntityBehaviorEmergeComponent;
    "minecraft:behavior.investigate_suspicious_location"?: EntityBehaviorInvestigateSuspiciousLocationComponent;
    "minecraft:behavior.roar"?: EntityBehaviorRoarComponent;
    "minecraft:behavior.sniff"?: EntityBehaviorSniffComponent;
    "minecraft:behavior.stay_near_noteblock"?: EntityBehaviorStayNearNoteblockComponent;
    "minecraft:behavior.random_search_and_dig"?: EntityBehaviorRandomSearchAndDigComponent;
    "minecraft:behavior.timer_flag_1"?: EntityBehaviorTimerFlag1Component;
    "minecraft:behavior.timer_flag_2"?: EntityBehaviorTimerFlag2Component;
    "minecraft:behavior.timer_flag_3"?: EntityBehaviorTimerFlag3Component;
    "minecraft:behavior.trade_with_player"?: EntityBehaviorTradeWithPlayerComponent;
    "minecraft:behavior.float"?: EntityBehaviorFloatComponent;
    "minecraft:behavior.take_flower"?: EntityBehaviorTakeFlowerComponent;
    "minecraft:behavior.random_look_around"?: EntityBehaviorRandomLookAroundComponent;
    "minecraft:behavior.random_look_around_and_sit"?: EntityBehaviorRandomLookAroundAndSitComponent;
    "minecraft:behavior.offer_flower"?: EntityBehaviorOfferFlowerComponent;
    "minecraft:behavior.play"?: EntityBehaviorPlayComponent;
    "minecraft:behavior.wither_target_highest_damage"?: EntityBehaviorWitherTargetHighestDamageComponent;
    "minecraft:behavior.vex_copy_owner_target"?: EntityBehaviorVexCopyOwnerTargetComponent;
    "minecraft:behavior.swim_with_entity"?: EntityBehaviorSwimWithEntityComponent;
    "minecraft:behavior.sneeze"?: EntityBehaviorSneezeComponent;
    "minecraft:behavior.share_items"?: EntityBehaviorShareItemsComponent;
    "minecraft:behavior.owner_hurt_target"?: EntityBehaviorOwnerHurtTargetComponent;
    "minecraft:behavior.owner_hurt_by_target"?: EntityBehaviorOwnerHurtByTargetComponent;
    "minecraft:behavior.nearest_attackable_target"?: EntityBehaviorNearestAttackableTargetComponent;
    "minecraft:behavior.hurt_by_target"?: EntityBehaviorHurtByTargetComponent;
    "minecraft:behavior.follow_caravan"?: EntityBehaviorFollowCaravanComponent;
    "minecraft:behavior.drop_item_for"?: EntityBehaviorDropItemForComponent;
    "minecraft:behavior.delayed_attack"?: EntityBehaviorDelayedAttackComponent;
    "minecraft:behavior.defend_village_target"?: EntityBehaviorDefendVillageTargetComponent;
    "minecraft:behavior.defend_trusted_target"?: EntityBehaviorDefendTrustedTargetComponent;
    "minecraft:behavior.avoid_mob_type"?: EntityBehaviorAvoidMobTypeComponent;
    "minecraft:behavior.nearest_prioritized_attackable_target"?: EntityBehaviorNearestPrioritizedAttackableTargetComponent;
    "minecraft:behavior.drink_milk"?: EntityBehaviorDrinkMilkComponent;
    "minecraft:behavior.pickup_items"?: EntityBehaviorPickupItemsComponent;
    "minecraft:behavior.move_to_block"?: EntityBehaviorMoveToBlockComponent;
    "minecraft:behavior.sleep"?: EntityBehaviorSleepComponent;
    "minecraft:behavior.follow_owner"?: EntityBehaviorFollowOwnerComponent;
    "minecraft:behavior.work_composter"?: EntityBehaviorWorkComposterComponent;
    "minecraft:behavior.knockback_roar"?: EntityBehaviorKnockbackRoarComponent;
    "minecraft:behavior.go_home"?: EntityBehaviorGoHomeComponent;
    "minecraft:behavior.lay_egg"?: EntityBehaviorLayEggComponent;
    "minecraft:behavior.melee_attack"?: EntityBehaviorMeleeAttackComponent;
    "minecraft:behavior.melee_box_attack"?: EntityBehaviorMeleeBoxAttackComponent;
    "minecraft:behavior.play_dead"?: EntityBehaviorPlayDeadComponent;
    "minecraft:behavior.jump_to_block"?: EntityBehaviorJumpToBlockComponent;
    "minecraft:behavior.ram_attack"?: EntityBehaviorRamAttackComponent;
    "minecraft:behavior.move_towards_dwelling_restriction"?: EntityBehaviorMoveTowardsDwellingRestrictionComponent;
    "minecraft:behavior.move_towards_home_restriction"?: EntityBehaviorMoveTowardsHomeRestrictionComponent;
    "minecraft:behavior.send_event"?: EntityBehaviorSendEventComponent;
    "minecraft:behavior.admire_item"?: EntityBehaviorAdmireItemComponent;
    "minecraft:behavior.avoid_block"?: EntityBehaviorAvoidBlockComponent;
    "minecraft:behavior.barter"?: EntityBehaviorBarterComponent;
    "minecraft:behavior.beg"?: EntityBehaviorBegComponent;
    "minecraft:behavior.break_door"?: EntityBehaviorBreakDoorComponent;
    "minecraft:behavior.breed"?: EntityBehaviorBreedComponent;
    "minecraft:behavior.celebrate_survive"?: EntityBehaviorCelebrateSurviveComponent;
    "minecraft:behavior.celebrate"?: EntityBehaviorCelebrateComponent;
    "minecraft:behavior.charge_attack"?: EntityBehaviorChargeAttackComponent;
    "minecraft:behavior.charge_held_item"?: EntityBehaviorChargeHeldItemComponent;
    "minecraft:behavior.circle_around_anchor"?: EntityBehaviorCircleAroundAnchorComponent;
    "minecraft:behavior.controlled_by_player"?: EntityBehaviorControlledByPlayerComponent;
    "minecraft:behavior.door_interact"?: EntityBehaviorDoorInteractComponent;
    "minecraft:behavior.drink_potion"?: EntityBehaviorDrinkPotionComponent;
    "minecraft:behavior.dragonlanding"?: EntityBehaviorDragonlandingComponent;
    "minecraft:behavior.dragonscanning"?: EntityBehaviorDragonscanningComponent;
    "minecraft:behavior.dragontakeoff"?: EntityBehaviorDragontakeoffComponent;
    "minecraft:behavior.dragonchargeplayer"?: EntityBehaviorDragonchargeplayerComponent;
    "minecraft:behavior.dragonstrafeplayer"?: EntityBehaviorDragonstrafeplayerComponent;
    "minecraft:behavior.dragonholdingpattern"?: EntityBehaviorDragonholdingpatternComponent;
    "minecraft:behavior.dragondeath"?: EntityBehaviorDragondeathComponent;
    "minecraft:behavior.dragonflaming"?: EntityBehaviorDragonflamingComponent;
    "minecraft:behavior.eat_block"?: EntityBehaviorEatBlockComponent;
    "minecraft:behavior.eat_carried_item"?: EntityBehaviorEatCarriedItemComponent;
    "minecraft:behavior.enderman_leave_block"?: EntityBehaviorEndermanLeaveBlockComponent;
    "minecraft:behavior.enderman_take_block"?: EntityBehaviorEndermanTakeBlockComponent;
    "minecraft:behavior.equip_item"?: EntityBehaviorEquipItemComponent;
    "minecraft:behavior.explore_outskirts"?: EntityBehaviorExploreOutskirtsComponent;
    "minecraft:behavior.fertilize_farm_block"?: EntityBehaviorFertilizeFarmBlockComponent;
    "minecraft:behavior.find_cover"?: EntityBehaviorFindCoverComponent;
    "minecraft:behavior.find_mount"?: EntityBehaviorFindMountComponent;
    "minecraft:behavior.find_underwater_treasure"?: EntityBehaviorFindUnderwaterTreasureComponent;
    "minecraft:behavior.flee_sun"?: EntityBehaviorFleeSunComponent;
    "minecraft:behavior.float_wander"?: EntityBehaviorFloatWanderComponent;
    "minecraft:behavior.follow_mob"?: EntityBehaviorFollowMobComponent;
    "minecraft:behavior.follow_parent"?: EntityBehaviorFollowParentComponent;
    "minecraft:behavior.follow_target_captain"?: EntityBehaviorFollowTargetCaptainComponent;
    "minecraft:behavior.guardian_attack"?: EntityBehaviorGuardianAttackComponent;
    "minecraft:behavior.harvest_farm_block"?: EntityBehaviorHarvestFarmBlockComponent;
    "minecraft:behavior.hide"?: EntityBehaviorHideComponent;
    "minecraft:behavior.hold_ground"?: EntityBehaviorHoldGroundComponent;
    "minecraft:behavior.hover"?: EntityBehaviorHoverComponent;
    "minecraft:behavior.inspect_bookshelf"?: EntityBehaviorInspectBookshelfComponent;
    "minecraft:behavior.lay_down"?: EntityBehaviorLayDownComponent;
    "minecraft:behavior.leap_at_target"?: EntityBehaviorLeapAtTargetComponent;
    "minecraft:behavior.look_at_entity"?: EntityBehaviorLookAtEntityComponent;
    "minecraft:behavior.look_at_player"?: EntityBehaviorLookAtPlayerComponent;
    "minecraft:behavior.look_at_target"?: EntityBehaviorLookAtTargetComponent;
    "minecraft:behavior.look_at_trading_player"?: EntityBehaviorLookAtTradingPlayerComponent;
    "minecraft:behavior.make_love"?: EntityBehaviorMakeLoveComponent;
    "minecraft:behavior.mingle"?: EntityBehaviorMingleComponent;
    "minecraft:behavior.mount_pathing"?: EntityBehaviorMountPathingComponent;
    "minecraft:behavior.move_indoors"?: EntityBehaviorMoveIndoorsComponent;
    "minecraft:behavior.move_outdoors"?: EntityBehaviorMoveOutdoorsComponent;
    "minecraft:behavior.move_through_village"?: EntityBehaviorMoveThroughVillageComponent;
    "minecraft:behavior.move_towards_target"?: EntityBehaviorMoveTowardsTargetComponent;
    "minecraft:behavior.move_to_land"?: EntityBehaviorMoveToLandComponent;
    "minecraft:behavior.move_to_poi"?: EntityBehaviorMoveToPoiComponent;
    "minecraft:behavior.move_to_lava"?: EntityBehaviorMoveToLavaComponent;
    "minecraft:behavior.move_to_liquid"?: EntityBehaviorMoveToLiquidComponent;
    "minecraft:behavior.move_to_random_block"?: EntityBehaviorMoveToRandomBlockComponent;
    "minecraft:behavior.move_to_village"?: EntityBehaviorMoveToVillageComponent;
    "minecraft:behavior.move_to_water"?: EntityBehaviorMoveToWaterComponent;
    "minecraft:behavior.nap"?: EntityBehaviorNapComponent;
    "minecraft:behavior.ocelotattack"?: EntityBehaviorOcelotattackComponent;
    "minecraft:behavior.ocelot_sit_on_block"?: EntityBehaviorOcelotSitOnBlockComponent;
    "minecraft:behavior.open_door"?: EntityBehaviorOpenDoorComponent;
    "minecraft:behavior.panic"?: EntityBehaviorPanicComponent;
    "minecraft:behavior.pet_sleep_with_owner"?: EntityBehaviorPetSleepWithOwnerComponent;
    "minecraft:behavior.player_ride_tamed"?: EntityBehaviorPlayerRideTamedComponent;
    "minecraft:behavior.raid_garden"?: EntityBehaviorRaidGardenComponent;
    "minecraft:behavior.random_breach"?: EntityBehaviorRandomBreachComponent;
    "minecraft:behavior.random_fly"?: EntityBehaviorRandomFlyComponent;
    "minecraft:behavior.random_hover"?: EntityBehaviorRandomHoverComponent;
    "minecraft:behavior.random_sitting"?: EntityBehaviorRandomSittingComponent;
    "minecraft:behavior.random_stroll"?: EntityBehaviorRandomStrollComponent;
    "minecraft:behavior.random_swim"?: EntityBehaviorRandomSwimComponent;
    "minecraft:behavior.swim_up_for_breath"?: EntityBehaviorSwimUpForBreathComponent;
    "minecraft:behavior.ranged_attack"?: EntityBehaviorRangedAttackComponent;
    "minecraft:behavior.recieve_love"?: EntityBehaviorRecieveLoveComponent;
    "minecraft:behavior.restrict_sun"?: EntityBehaviorRestrictSunComponent;
    "minecraft:behavior.restrict_open_door"?: EntityBehaviorRestrictOpenDoorComponent;
    "minecraft:behavior.rise_to_liquid_level"?: EntityBehaviorRiseToLiquidLevelComponent;
    "minecraft:behavior.roll"?: EntityBehaviorRollComponent;
    "minecraft:behavior.run_around_like_crazy"?: EntityBehaviorRunAroundLikeCrazyComponent;
    "minecraft:behavior.scared"?: EntityBehaviorScaredComponent;
    "minecraft:behavior.skeleton_horse_trap"?: EntityBehaviorSkeletonHorseTrapComponent;
    "minecraft:behavior.silverfish_wake_up_friends"?: EntityBehaviorSilverfishWakeUpFriendsComponent;
    "minecraft:behavior.silverfish_merge_with_stone"?: EntityBehaviorSilverfishMergeWithStoneComponent;
    "minecraft:behavior.slime_float"?: EntityBehaviorSlimeFloatComponent;
    "minecraft:behavior.slime_attack"?: EntityBehaviorSlimeAttackComponent;
    "minecraft:behavior.slime_random_direction"?: EntityBehaviorSlimeRandomDirectionComponent;
    "minecraft:behavior.slime_keep_on_jumping"?: EntityBehaviorSlimeKeepOnJumpingComponent;
    "minecraft:behavior.snacking"?: EntityBehaviorSnackingComponent;
    "minecraft:behavior.squid_move_away_from_ground"?: EntityBehaviorSquidMoveAwayFromGroundComponent;
    "minecraft:behavior.squid_flee"?: EntityBehaviorSquidFleeComponent;
    "minecraft:behavior.squid_idle"?: EntityBehaviorSquidIdleComponent;
    "minecraft:behavior.squid_dive"?: EntityBehaviorSquidDiveComponent;
    "minecraft:behavior.squid_out_of_water"?: EntityBehaviorSquidOutOfWaterComponent;
    "minecraft:behavior.stalk_and_pounce_on_target"?: EntityBehaviorStalkAndPounceOnTargetComponent;
    "minecraft:behavior.stay_while_sitting"?: EntityBehaviorStayWhileSittingComponent;
    "minecraft:behavior.stomp_attack"?: EntityBehaviorStompAttackComponent;
    "minecraft:behavior.stomp_turtle_egg"?: EntityBehaviorStompTurtleEggComponent;
    "minecraft:behavior.stroll_towards_village"?: EntityBehaviorStrollTowardsVillageComponent;
    "minecraft:behavior.summon_entity"?: EntityBehaviorSummonEntityComponent;
    "minecraft:behavior.swell"?: EntityBehaviorSwellComponent;
    "minecraft:behavior.swim_idle"?: EntityBehaviorSwimIdleComponent;
    "minecraft:behavior.swim_wander"?: EntityBehaviorSwimWanderComponent;
    "minecraft:behavior.swoop_attack"?: EntityBehaviorSwoopAttackComponent;
    "minecraft:behavior.tempt"?: EntityBehaviorTemptComponent;
    "minecraft:behavior.trade_interest"?: EntityBehaviorTradeInterestComponent;
    "minecraft:behavior.vex_random_move"?: EntityBehaviorVexRandomMoveComponent;
    "minecraft:behavior.wither_random_attack_pos_goal"?: EntityBehaviorWitherRandomAttackPosGoalComponent;
    "minecraft:behavior.work"?: EntityBehaviorWorkComponent;
    "minecraft:behavior.fire_at_target"?: EntityBehaviorFireAtTargetComponent;
    "minecraft:behavior.move_around_target"?: EntityBehaviorMoveAroundTargetComponent;
    "minecraft:behavior.jump_around_target"?: EntityBehaviorJumpAroundTargetComponent;
    "minecraft:behavior.teleport_to_owner"?: EntityBehaviorTeleportToOwnerComponent;
    "minecraft:behavior.float_tempt"?: EntityBehaviorFloatTemptComponent;
    "minecraft:behavior.place_block"?: EntityBehaviorPlaceBlockComponent;
    "minecraft:behavior.take_block"?: EntityBehaviorTakeBlockComponent;
    "minecraft:behavior.move_away_from_target"?: EntityBehaviorMoveAwayFromTargetComponent;
    "minecraft:behavior.sonic_boom"?: EntityBehaviorSonicBoomComponent;
  };
}
export type EntityComponents = {
  "minecraft:vibration_listener"?: EntityVibrationListenerComponent;
  "minecraft:anger_level"?: EntityAngerLevelComponent;
  "minecraft:heartbeat"?: EntityHeartbeatComponent;
  "minecraft:suspect_tracking"?: EntitySuspectTrackingComponent;
  "minecraft:vibration_damper"?: EntityVibrationDamperComponent;
  "minecraft:variable_max_auto_step"?: EntityVariableMaxAutoStepComponent;
  "minecraft:shooter"?: EntityShooterComponent;
  "minecraft:inventory"?: EntityInventoryComponent;
  "minecraft:physics"?: EntityPhysicsComponent;
  "minecraft:area_attack"?: EntityAreaAttackComponent;
  "minecraft:dash"?: EntityDashComponent;
  "minecraft:game_event_movement_tracking"?: EntityGameEventMovementTrackingComponent;
  "minecraft:mob_effect"?: EntityMobEffectComponent;
  "minecraft:movement_sound_distance_offset"?: EntityMovementSoundDistanceOffsetComponent;
  "minecraft:ambient_sound_interval"?: EntityAmbientSoundIntervalComponent;
  "minecraft:interact"?: EntityInteractComponent;
  "minecraft:block_sensor"?: EntityBlockSensorComponent;
  "minecraft:exhaustion_values"?: EntityExhaustionValuesComponent;
  "minecraft:shareables"?: EntityShareablesComponent;
  "minecraft:block_climber"?: EntityBlockClimberComponent;
  "minecraft:body_rotation_blocked"?: EntityBodyRotationBlockedComponent;
  "minecraft:drying_out_timer"?: EntityDryingOutTimerComponent;
  "minecraft:genetics"?: EntityGeneticsComponent;
  "minecraft:ageable"?: EntityAgeableComponent;
  "minecraft:combat_regeneration"?: EntityCombatRegenerationComponent;
  "minecraft:breedable"?: EntityBreedableComponent;
  "minecraft:damage_sensor"?: EntityDamageSensorComponent;
  "minecraft:navigation.climb"?: EntityNavigationClimbComponent;
  "minecraft:navigation.float"?: EntityNavigationFloatComponent;
  "minecraft:navigation.fly"?: EntityNavigationFlyComponent;
  "minecraft:navigation.generic"?: EntityNavigationGenericComponent;
  "minecraft:navigation.hover"?: EntityNavigationHoverComponent;
  "minecraft:navigation.swim"?: EntityNavigationSwimComponent;
  "minecraft:navigation.walk"?: EntityNavigationWalkComponent;
  "minecraft:bribeable"?: EntityBribeableComponent;
  "minecraft:inside_block_notifier"?: EntityInsideBlockNotifierComponent;
  "minecraft:conditional_bandwidth_optimization"?: EntityConditionalBandwidthOptimizationComponent;
  "minecraft:equippable"?: EntityEquippableComponent;
  "minecraft:giveable"?: EntityGiveableComponent;
  "minecraft:healable"?: EntityHealableComponent;
  "minecraft:out_of_control"?: EntityOutOfControlComponent;
  "minecraft:tamemount"?: EntityTamemountComponent;
  "minecraft:addrider"?: EntityAddriderComponent;
  "minecraft:admire_item"?: EntityAdmireItemComponent;
  "minecraft:angry"?: EntityAngryComponent;
  "minecraft:attack"?: EntityAttackComponent;
  "minecraft:attack_cooldown"?: EntityAttackCooldownComponent;
  "minecraft:attack_damage"?: EntityAttackDamageComponent;
  "minecraft:balloonable"?: EntityBalloonableComponent;
  "minecraft:barter"?: EntityBarterComponent;
  "minecraft:boostable"?: EntityBoostableComponent;
  "minecraft:boss"?: EntityBossComponent;
  "minecraft:break_blocks"?: EntityBreakBlocksComponent;
  "minecraft:breathable"?: EntityBreathableComponent;
  "minecraft:buoyant"?: EntityBuoyantComponent;
  "minecraft:burns_in_daylight"?: EntityBurnsInDaylightComponent;
  "minecraft:can_climb"?: EntityCanClimbComponent;
  "minecraft:can_fly"?: EntityCanFlyComponent;
  "minecraft:celebrate_hunt"?: EntityCelebrateHuntComponent;
  "minecraft:collision_box"?: EntityCollisionBoxComponent;
  "minecraft:color"?: EntityColorComponent;
  "minecraft:color2"?: EntityColor2Component;
  "minecraft:custom_hit_test"?: EntityCustomHitTestComponent;
  "minecraft:damage_over_time"?: EntityDamageOverTimeComponent;
  "minecraft:default_look_angle"?: EntityDefaultLookAngleComponent;
  "minecraft:despawn"?: EntityDespawnComponent;
  "minecraft:dweller"?: EntityDwellerComponent;
  "minecraft:economy_trade_table"?: EntityEconomyTradeTableComponent;
  "minecraft:environment_sensor"?: EntityEnvironmentSensorComponent;
  "minecraft:entity_sensor"?: EntityEntitySensorComponent;
  "minecraft:equipment"?: EntityEquipmentComponent;
  "minecraft:equip_item"?: EntityEquipItemComponent;
  "minecraft:experience_reward"?: EntityExperienceRewardComponent;
  "minecraft:explode"?: EntityExplodeComponent;
  "minecraft:fire_immune"?: EntityFireImmuneComponent;
  "minecraft:floats_in_liquid"?: EntityFloatsInLiquidComponent;
  "minecraft:flocking"?: EntityFlockingComponent;
  "minecraft:flying_speed"?: EntityFlyingSpeedComponent;
  "minecraft:follow_range"?: EntityFollowRangeComponent;
  "minecraft:friction_modifier"?: EntityFrictionModifierComponent;
  "minecraft:ground_offset"?: EntityGroundOffsetComponent;
  "minecraft:group_size"?: EntityGroupSizeComponent;
  "minecraft:grows_crop"?: EntityGrowsCropComponent;
  "minecraft:health"?: EntityHealthComponent;
  "minecraft:hide"?: EntityHideComponent;
  "minecraft:home"?: EntityHomeComponent;
  "minecraft:horse.jump_strength"?: EntityHorseJumpStrengthComponent;
  "minecraft:hurt_on_condition"?: EntityHurtOnConditionComponent;
  "minecraft:input_ground_controlled"?: EntityInputGroundControlledComponent;
  "minecraft:insomnia"?: EntityInsomniaComponent;
  "minecraft:instant_despawn"?: EntityInstantDespawnComponent;
  "minecraft:is_baby"?: EntityIsBabyComponent;
  "minecraft:is_charged"?: EntityIsChargedComponent;
  "minecraft:is_chested"?: EntityIsChestedComponent;
  "minecraft:is_dyeable"?: EntityIsDyeableComponent;
  "minecraft:is_hidden_when_invisible"?: EntityIsHiddenWhenInvisibleComponent;
  "minecraft:is_ignited"?: EntityIsIgnitedComponent;
  "minecraft:is_illager_captain"?: EntityIsIllagerCaptainComponent;
  "minecraft:is_saddled"?: EntityIsSaddledComponent;
  "minecraft:is_shaking"?: EntityIsShakingComponent;
  "minecraft:is_sheared"?: EntityIsShearedComponent;
  "minecraft:is_stackable"?: EntityIsStackableComponent;
  "minecraft:is_stunned"?: EntityIsStunnedComponent;
  "minecraft:is_tamed"?: EntityIsTamedComponent;
  "minecraft:item_controllable"?: EntityItemControllableComponent;
  "minecraft:item_hopper"?: EntityItemHopperComponent;
  "minecraft:jump.static"?: EntityJumpStaticComponent;
  "minecraft:jump.dynamic"?: EntityJumpDynamicComponent;
  "minecraft:knockback_resistance"?: EntityKnockbackResistanceComponent;
  "minecraft:lava_movement"?: EntityLavaMovementComponent;
  "minecraft:leashable"?: EntityLeashableComponent;
  "minecraft:loot"?: EntityLootComponent;
  "minecraft:managed_wandering_trader"?: EntityManagedWanderingTraderComponent;
  "minecraft:mark_variant"?: EntityMarkVariantComponent;
  "minecraft:movement"?: EntityMovementComponent;
  "minecraft:movement.amphibious"?: EntityMovementAmphibiousComponent;
  "minecraft:movement.basic"?: EntityMovementBasicComponent;
  "minecraft:movement.fly"?: EntityMovementFlyComponent;
  "minecraft:movement.generic"?: EntityMovementGenericComponent;
  "minecraft:movement.hover"?: EntityMovementHoverComponent;
  "minecraft:movement.jump"?: EntityMovementJumpComponent;
  "minecraft:movement.glide"?: EntityMovementGlideComponent;
  "minecraft:skin_id"?: EntitySkinIdComponent;
  "minecraft:movement.skip"?: EntityMovementSkipComponent;
  "minecraft:movement.sway"?: EntityMovementSwayComponent;
  "minecraft:nameable"?: EntityNameableComponent;
  "minecraft:npc"?: EntityNpcComponent;
  "minecraft:on_death"?: EntityOnDeathComponent;
  "minecraft:on_friendly_anger"?: EntityOnFriendlyAngerComponent;
  "minecraft:on_hurt"?: EntityOnHurtComponent;
  "minecraft:on_hurt_by_player"?: EntityOnHurtByPlayerComponent;
  "minecraft:on_ignite"?: EntityOnIgniteComponent;
  "minecraft:on_start_landing"?: EntityOnStartLandingComponent;
  "minecraft:on_start_takeoff"?: EntityOnStartTakeoffComponent;
  "minecraft:on_target_acquired"?: EntityOnTargetAcquiredComponent;
  "minecraft:on_target_escape"?: EntityOnTargetEscapeComponent;
  "minecraft:on_wake_with_owner"?: EntityOnWakeWithOwnerComponent;
  "minecraft:peek"?: EntityPeekComponent;
  "minecraft:persistent"?: EntityPersistentComponent;
  "minecraft:player.saturation"?: EntityPlayerSaturationComponent;
  "minecraft:player.exhaustion"?: EntityPlayerExhaustionComponent;
  "minecraft:player.level"?: EntityPlayerLevelComponent;
  "minecraft:player.experience"?: EntityPlayerExperienceComponent;
  "minecraft:pushable"?: EntityPushableComponent;
  "minecraft:push_through"?: EntityPushThroughComponent;
  "minecraft:preferred_path"?: EntityPreferredPathComponent;
  "minecraft:projectile"?: EntityProjectileComponent;
  "minecraft:raid_trigger"?: EntityRaidTriggerComponent;
  "minecraft:rail_movement"?: EntityRailMovementComponent;
  "minecraft:rail_sensor"?: EntityRailSensorComponent;
  "minecraft:ravager_blocked"?: EntityRavagerBlockedComponent;
  "minecraft:rideable"?: EntityRideableComponent;
  "minecraft:scale"?: EntityScaleComponent;
  "minecraft:scale_by_age"?: EntityScaleByAgeComponent;
  "minecraft:scheduler"?: EntitySchedulerComponent;
  "minecraft:sittable"?: EntitySittableComponent;
  "minecraft:sound_volume"?: EntitySoundVolumeComponent;
  "minecraft:spawn_entity"?: EntitySpawnEntityComponent;
  "minecraft:spell_effects"?: EntitySpellEffectsComponent;
  "minecraft:strength"?: EntityStrengthComponent;
  "minecraft:tameable"?: EntityTameableComponent;
  "minecraft:target_nearby_sensor"?: EntityTargetNearbySensorComponent;
  "minecraft:teleport"?: EntityTeleportComponent;
  "minecraft:tick_world"?: EntityTickWorldComponent;
  "minecraft:timer"?: EntityTimerComponent;
  "minecraft:trade_resupply"?: EntityTradeResupplyComponent;
  "minecraft:trade_table"?: EntityTradeTableComponent;
  "minecraft:trail"?: EntityTrailComponent;
  "minecraft:transformation"?: EntityTransformationComponent;
  "minecraft:trusting"?: EntityTrustingComponent;
  "minecraft:trust"?: EntityTrustComponent;
  "minecraft:type_family"?: EntityTypeFamilyComponent;
  "minecraft:underwater_movement"?: EntityUnderwaterMovementComponent;
  "minecraft:variant"?: EntityVariantComponent;
  "minecraft:walk_animation_speed"?: EntityWalkAnimationSpeedComponent;
  "minecraft:wants_jockey"?: EntityWantsJockeyComponent;
  "minecraft:water_movement"?: EntityWaterMovementComponent;
  "minecraft:can_join_raid"?: EntityCanJoinRaidComponent;
  "minecraft:reflect_projectiles"?: EntityReflectProjectilesComponent;
  "minecraft:wind_burst"?: EntityWindBurstComponent;
  "minecraft:mob_effect_immunity"?: EntityMobEffectImmunityComponent;
  "minecraft:dimension_bound"?: EntityDimensionBoundComponent;
  "minecraft:transient"?: EntityTransientComponent;
  "minecraft:looked_at"?: EntityLookedAtComponent;
  "minecraft:cannot_be_attacked"?: EntityCannotBeAttackedComponent;
  "minecraft:ignore_cannot_be_attacked"?: EntityIgnoreCannotBeAttackedComponent;
  "minecraft:renders_when_invisible"?: EntityRendersWhenInvisibleComponent;
  "minecraft:is_collidable"?: EntityIsCollidableComponent;
  "minecraft:input_air_controlled"?: EntityInputAirControlledComponent;
  "minecraft:body_rotation_always_follows_head"?: EntityBodyRotationAlwaysFollowsHeadComponent;
  "minecraft:leashable_to"?: EntityLeashableToComponent;
  "minecraft:remove_in_peaceful"?: EntityRemoveInPeacefulComponent;
  "minecraft:rotation_axis_aligned"?: EntityRotationAxisAlignedComponent;
  "minecraft:can_power_jump"?: EntityCanPowerJumpComponent;
} & EntityComponents.Annotations &
  EntityComponents.Behaviors;
